# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tag.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tag.proto',
  package='tag',
  syntax='proto3',
  serialized_pb=_b('\n\ttag.proto\x12\x03tag\"\xa2\x01\n\x04\x44\x61ta\x12\x1e\n\x05image\x18\x01 \x03(\x0b\x32\x0f.tag.Data.Image\x1az\n\x05Image\x12\x0b\n\x03url\x18\x01 \x01(\t\x12(\n\x07\x66\x65\x61ture\x18\x02 \x03(\x0b\x32\x17.tag.Data.Image.Feature\x12\x0c\n\x04tags\x18\x03 \x01(\t\x1a,\n\x07\x46\x65\x61ture\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x62\x06proto3')
)




_DATA_IMAGE_FEATURE = _descriptor.Descriptor(
  name='Feature',
  full_name='tag.Data.Image.Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='tag.Data.Image.Feature.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='tag.Data.Image.Feature.confidence', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=181,
)

_DATA_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='tag.Data.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='tag.Data.Image.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature', full_name='tag.Data.Image.feature', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='tag.Data.Image.tags', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATA_IMAGE_FEATURE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=181,
)

_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='tag.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='tag.Data.image', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATA_IMAGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=181,
)

_DATA_IMAGE_FEATURE.containing_type = _DATA_IMAGE
_DATA_IMAGE.fields_by_name['feature'].message_type = _DATA_IMAGE_FEATURE
_DATA_IMAGE.containing_type = _DATA
_DATA.fields_by_name['image'].message_type = _DATA_IMAGE
DESCRIPTOR.message_types_by_name['Data'] = _DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(

  Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(

    Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), dict(
      DESCRIPTOR = _DATA_IMAGE_FEATURE,
      __module__ = 'tag_pb2'
      # @@protoc_insertion_point(class_scope:tag.Data.Image.Feature)
      ))
    ,
    DESCRIPTOR = _DATA_IMAGE,
    __module__ = 'tag_pb2'
    # @@protoc_insertion_point(class_scope:tag.Data.Image)
    ))
  ,
  DESCRIPTOR = _DATA,
  __module__ = 'tag_pb2'
  # @@protoc_insertion_point(class_scope:tag.Data)
  ))
_sym_db.RegisterMessage(Data)
_sym_db.RegisterMessage(Data.Image)
_sym_db.RegisterMessage(Data.Image.Feature)


# @@protoc_insertion_point(module_scope)
