#FROM tensorflow/tensorflow 
FROM erroneousboat/tensorflow-python3-jupyter
RUN apt-get update
RUN apt-get install python3-pip -y
RUN pip3 install requests
RUN pip3 install clarifai
#RUN pip3 install protobuf
RUN pip3 install -U scikit-learn
